### PR TITLE
Expand on “don’t write fiction”

### LINKED ISSUE #99: Working Mode: describe "don't write fiction" rule as joint responsibility of editor and implementers
I made this comment on a draft of a different charter, and @hober pointed out the wording I was commenting on came from the WHATWG working mode, where I think it applies equally.

Currently, the working mode says:

> The editor has the following responsibilities, all of which can be delegated to deputy editors:
> 
> * Ensure any applied changes fulfill the relevant criteria for changes.
> * Resolve conflicts between contributors.
> * Reduce open issues.
> * Help manage the corresponding tests.
> * Ensure implementations follow the standard and vice versa. (The “don’t write fiction” rule.) 

I think the last of these is a little bit different from the first four, because the first four are things that the editor can really be expected to be fully responsible for.  The last one, however, can't be done without the participation of implementers.  For example, when implementers choose not to follow the specification, they need to tell the editor about it (file issues) rather than just silently do something else.  Likewise implementers have some responsibility to review the specification to check that what the editor has written matches those implementations -- and editors also have some responsibility to solicit/extract this review from implementers.

So my suggested wording change was just the addition of a parenthetical:

> * Ensure (together with implementers) that implementations follow the standard and vice versa. (The “don’t write fiction” rule.) 

although I'm sure there are better ways to word this.

### PR DESCRIPTION
**Pull request by annevk**
Closes #99.

### CODE REVIEW

**Comment by michaelchampion** [comment]
This probably a more meta-issue than a comment on this PR, but here goes: Should the "more concretely" bullets say anything about use in websites or interest from major website developers as well as "implementers?"  Or does "implementer" imply both browser platform developers and website / webapp / framework  developers?

It would be good to make the success criteria clear, but I don't have a strong opinion on whether this is the right place to state them.  Nor am I convinced there is a real problem with features that get implemented in browsers but not used on the web; I worked on a browser team long enough to appreciate that they (now anyway) pay attention to user-side demand before investing in supplying a platform implementation.  

Thoughts on whether this is worth discussing,  and where is the right place to discuss it,  would be appreciated.

**Comment by othermaciej** [comment]
Could you file an issue on this? It looks substantive so should probably be an SG decision.

(For the record I support this change.)

**Comment by othermaciej** [comment]
Never mind, I saw there already is an issue. I’ll put it on the SG agenda and sign off there.

**Comment by annevk** [comment]
@whatwg/sg ping.

**Comment by foolip** [comment]
We have 3/4 now, so I'll go ahead and merge to get it done. @dbaron my guess is that it's very unlikely you would disagree, but please raise it if there's anything wrong here.

**Pull request merged**
