### PR TITLE
Make Philip the editor of Fullscreen

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
This as suggested by @annevk. Recently I've been the most active in making spec changes and maintaining the tests.

**Comment by annevk** [comment]
(I proposed this.)

**Comment by dbaron** [comment]
Sounds good to me.

**Comment by othermaciej** [comment]
I also support this. Filed #61 to ask for approval from the other two SG members.

**Comment by henceproved** [comment]
We have all SG reps approval either here or on https://github.com/whatwg/sg/issues/61, so merging.

**Pull request merged**
