### PR TITLE
Change Patent Licensing Obligation subtypes into definitions

### LINKED ISSUE #95: Circular reference in the WHATWG IPR policy / bug in the contribution license
Section [5.2. Contribution Licensing Obligations](https://whatwg.org/ipr-policy#52-contribution-licensing-obligations) consists of the following text (emphasis mine):

> For each Contribution, the **_Contribution Licensing Obligations_** are effective irrevocably on the 45th Day after the Contribution was first made.

The part emphasized is a link, a circular reference back that same sections' title. This fails to achieve the intended effect, which was to say what kind of obligations are effective on the 45th day.

I believe that instead, the text of that link was intended to be "Patent Licensing Obligation", and to link to [2.6. "Patent Licensing Obligation"](https://whatwg.org/ipr-policy#26-patent-licensing-obligation)

### PR DESCRIPTION
**Pull request by annevk**
And reference them from rather than referencing the 5.2 and 5.3 sections that deal with time periods.

(This intentionally does not change the references in 2.8.2 that are about the time periods.)

Closes #95.

### CODE REVIEW

**Review by foolip — APPROVED** [review]
Nice cleanup, thanks!

**Review by travisleithead — APPROVED** [review]
The changes seem like pure linking/definition improvement and do not appear to substantively change the IPR policy in any way.

**Comment by foolip** [comment]
@othermaciej can you take a look at this as well?

**Review by tantek — APPROVED** [review]
LGTM

**Pull request merged**
