### PR TITLE
Update some editors who have signed the agreement

### PR DESCRIPTION
**Pull request by domenic**

### CODE REVIEW

**Comment by othermaciej** [comment]
Although I believe this is correct and not likely to be controversial, I think it's a substantive change so would appreciate confirmation from @dbaron @henceproved @michaelchampion before approving this PR.

**Comment by michaelchampion** [comment]
Ok by me

**Comment by henceproved** [comment]
Looks good to me.

**Comment by dbaron** [comment]
Fine with me as well.  (I also checked that all three are verified: true in individuals.json.)

**Pull request merged**
