### PR TITLE
Remove year from example LICENSE file

### PR DESCRIPTION
**Pull request by foolip**
Closes https://github.com/whatwg/sg/issues/102.

### CODE REVIEW

**Comment by annevk** [comment]
This is not the example LICENSE file, right? Should we remove the year from all the `.md` files at the same time?

**Comment by foolip** [comment]
It actually is the example, linked from https://whatwg.org/workstream-policy#notice-for-repositories. This only works because the license of the policies is the same, with the exception of IPR Policy, which additionally points to ThirdPartyNotices/W3CLicenses.md.

I'll update the copyright years in the markdown files too.

**Comment by annevk** [comment]
Ah, we should also update that policy to not include the year.

**Comment by foolip** [comment]
This needs further updating, per https://github.com/whatwg/html/pull/5668/files#r444805488.

**Comment by annevk** [comment]
FWIW, this looks good now.

**Comment by foolip** [comment]
I’ve only merged this, not any of the related PRs in other repos, as I’m not at my computer.

**Pull request merged**
